gdbus-codegen-glibmm: fix SRC_URI to say git:// instead of https://
And set "protocol=https". I do not think the exact previous SRC_URI has
ever worked. Without this fix there is an error when fetching:

$ bitbake -c fetch gdbus-codegen-glibmm-native
...
ERROR: gdbus-codegen-glibmm-native-3.0.0-r0 do_fetch: No checksum specified
for ../gdbus-codegen-glibmm.git, please add at least one to the recipe:

Signed-off-by: Martin Ejdestig <mejdestig@luxoft.com>